version: '3'
services:

  caddy:
    image: abiosoft/caddy
    ports:
      - 80:80
      - 443:443
      - 80:80/udp
      - 443:443/udp
    volumes:
        - ./Caddyfile:/etc/Caddyfile
        - ./.caddy:/root/.caddy
    environment:
        ACME_AGREE: "true"
    command: ["--quic", "--conf", "/etc/Caddyfile", "--log", "stdout", "--agree=true"]

  privatebin:
    image: privatebin/nginx-fpm-alpine

