version: '3'

services:
  terraria:
    image: beardedio/terraria:tshock-latest
    ports:
      - 7777:7777
    volumes:
      - ./data:/config
    environment:
      world: world.wld
    restart: unless-stopped
    tty: true
    stdin_open: true
