#!/bin/env bash
cd ~/arch-profile/pcap-dnsproxy
#cat "" >  Hosts.conf
cat <<EOF>Hosts.conf
[Local Hosts]

Server=/github.com/119.29.29.29#53

[Hosts]

EOF
curl https://raw.githubusercontent.com/vokins/yhosts/master/hosts >> adhosts
sed -i 's/\ /\t/g' adhosts
sed -i 's/\t\t/\t/g' adhosts
#space to tab
./hosts2conf
#. to \.
grep ^[^#] myhosts >> Hosts.conf
grep ^[^#] adhosts >> Hosts.conf
rm adhosts
#do not output lines starts with #
sudo cp Hosts.conf /etc/pcap-dnsproxy/Hosts.conf
