#!/bin/env bash
cd ~/arch-profile/pcap-dnsproxy
#cat "" >  Hosts.conf
cat <<EOF>Hosts.conf
[Local Hosts]

Server=/github.com/119.29.29.29#53

[Hosts]

EOF
curl https://raw.githubusercontent.com/vokins/yhosts/master/hosts >> adhosts
perl -pi -e 's/(?<=[a-zA-Z])\./\\\./' adhosts
perl -pi -e 's/(?<=[a-zA-Z])\./\\\./' adhosts
perl -pi -e 's/(?<=[a-zA-Z])\./\\\./' adhosts
perl -pi -e 's/(?<=[a-zA-Z])\./\\\./' adhosts
perl -pi -e 's/(?<=[a-zA-Z])\./\\\./' adhosts
cat myhosts >> Hosts.conf
cat adhosts >> Hosts.conf
sudo cp Hosts.conf /etc/pcap-dnsproxy/Hosts.conf
