version: '2'
services:
  syncthing-server:
    container_name: relay-discovery
    image: t4skforce/syncthing-relay-discovery
    volumes:
      - ./certs:/home/syncthing/certs
    ports:
      - "22067:22067"
      - "22026:22026"
    restart: always
